tools:
    php_sim: false
    php_cpd: false
    php_pdepend: true
    php_analyzer: true
    external_code_coverage:
        timeout: 600 # Timeout in seconds.
filter:
    excluded_paths:
        - 'tests/*'
